---
- name: Playbook for Linux
  become: true
  become_method: ansible.builtin.sudo
  debugger: never
  gather_facts: true
  hosts: all
  vars:
    enable_cloudinit: false
    ansible_python_interpreter: auto
    ansible_python_interpreter_fallback:
      [
        "python3.13",
        "python3.12",
        "python3.11",
        "python3.10",
        "python3.9",
        "python3.8",
        "/usr/bin/python3",
        "python3",
      ]
  roles:
    - base
    - users
    - configure
    - clean
